#!/usr/bin/env bash

set -e

# Change dir to script dir
pushd "$(dirname "$BASH_SOURCE[0]")" > /dev/null
COMPOSE_FILE="docker-compose/main.yaml"

# TODO: set the udp recieve buffer limit
# sudo sysctl -w net.core.rmem_max=$((1024*1024*64))

docker-compose "$@"

# Change back to original directory
popd > /dev/null

